### PR TITLE
Towards a complete GIS app...

### PR DESCRIPTION
**Pull request by dnlkoch**
Within this PR you will find some improvements regarding the client generation out of the current shogun2 application context.

### CODE REVIEW

**Comment by marcjansen** [comment]
Looking through the diff this looks veeeery promising! Good work.

If only we could get rid of the guessing of tje mappanel. We should discuss/address this separately.

LVGTM! Please merge. If travis agrees, that is.

**Comment by KaiVolland** [comment]
Is this WIP?

**Comment by dnlkoch** [comment]
No. :facepunch:

**Comment by dnlkoch** [comment]
:v:

**Comment by marcjansen** [comment]
I just realize that there isn't any travis here...

**Comment by dnlkoch** [comment]
Feel free to implement :ghost:

**Pull request merged**
